### ISSUE TITLE
is this open source?

### ISSUE THREAD

**Issue by krishnakanthpps** [yass09/waticket-project-ratp#1]
If I want to reuse this app, can I use it? What kind of license is your app under?

**Comment by yass09** [comment]
Hi, this is not an app. Simply a prototype developed as webpage. Which country and for what purpose do you want to use it?

**Comment by krishnakanthpps** [comment]
For India. and building an web/mobile app to help people find better ways to reach from point a to point b inside city.

**Comment by yass09** [comment]
ok, if you provide me with the source code, yes
By the way the intent was to find the right ticket not to show a route.
